services:
  ansible_service:
    restart: always
    container_name: ansible_service
    build:
      context: .
      dockerfile: ansible-docker-settings/Dockerfile
    volumes:
      - ./ansible:/opt/ansible
    environment:
      - ANSIBLE_CONFIG=/opt/ansible/ansible.cfg
