---
# Reference: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker
- name: Linux Variables Load
  ansible.builtin.include_vars:
    file: ../../../variables/os_var/linux_var.yml

- name: AdGuard Home Directory Structures Creation
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ adguardhome_parent_dir }}"
    - "{{ adguardhome_parent_dir }}/work"
    - "{{ adguardhome_parent_dir }}/conf"

- name: Docker Compose File Creation
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ adguardhome_parent_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  register: docker_compose_file

- name: AdGuard Home Deployment
  community.docker.docker_compose_v2:
    project_src: "{{ adguardhome_parent_dir }}"
    pull: "{{ docker_image_pull_action }}"
    state: present
    remove_orphans: true