---
- name: Windows Variables Load
  ansible.builtin.include_vars:
    file: ../../../variables/os_var/windows_var.yml
    
- name: Hyper-V Parent Directory Creation If Not Exists
  ansible.windows.win_file:
    path: "{{ hyper_v_parent_dir }}"
    state: directory

- name: VM Subdirectory Creation If Not Exists
  ansible.windows.win_file:
    path: "{{ hyper_v_parent_dir }}\\{{ item.name }}"
    state: directory
  loop: "{{ hyper_v_vm_list }}"
  when: item.host == computer_name

- name: ISO Files' Existence on Remote Hyper-V Host Verification
  ansible.windows.win_stat:
    path: "{{ srv_iso_source_dir }}\\{{ item.iso_destination }}"
  loop: "{{ hyper_v_vm_list }}"
  when: item.host == computer_name
  register: iso_files

- name: ISO File Copy to Remote Hyper-V Host If Not Exists (Skipped on Pipeline)
  ansible.windows.win_copy:
    src: "{{ item.iso_source }}"
    dest: "{{ srv_iso_source_dir }}\\{{ item.iso_destination }}"
    force: false
  loop: "{{ iso_files.results }}"
  when:
    - item.stat is defined
    - not item.stat.exists
    - lookup('env', 'CI') == '' # Only runs if NOT on pipeline

- name: VM Creation
  khangvum.hyperv.vm:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    generation: "{{ item.generation }}"
    memory_startup_bytes: "{{ item.memory }}GB"
    cpu: "{{ item.cpu }}"
    path: "{{ hyper_v_parent_dir }}\\{{ item.name }}"
    vhd_path: "{{ hyper_v_parent_dir }}\\{{ item.name }}\\{{ item.name }}.vhdx"
    vhd_size_bytes: "{{ item.storage }}GB"
    iso_path: "{{ srv_iso_source_dir }}\\{{ item.iso_destination }}"
    secure_boot_template: "{{ item.secure_boot_template }}"
    tpm: "{{ item.tpm | bool }}"
    v_switches: "{{ hostvars[item.name].v_switches }}"
  loop: "{{ hyper_v_vm_list }}"
  when: item.host == computer_name

- name: VM Autostart and Autostop Configuration
  khangvum.hyperv.vm_automatic_action:
    name: "{{ item.name }}"
    auto_start_action: "{{ item.autostart }}"
    auto_stop_action: "{{ item.autostop }}"
  loop: "{{ hyper_v_vm_list }}"
  when: 
    - item.host == computer_name
    - item.state | default('present') == 'present'

- name: VM Power On
  khangvum.hyperv.vm_state:
    name: "{{ item.name }}"
    state: "{{ 'running' if item.power | bool else 'stopped' }}"
  loop: "{{ hyper_v_vm_list }}"
  when: item.host == computer_name