---
- name: Linux Variables Load
  ansible.builtin.include_vars:
    file: ../../../variables/os_var/linux_var.yml

- name: IP Forwarding Enablement
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/99-tailscale.conf
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: tailscale Directory Creation
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ tailscale_parent_dir }}"
    - "{{ tailscale_parent_dir }}/state"

- name: Docker Compose File Creation
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ tailscale_parent_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  register: docker_compose_file

- name: Tailscale Deployment
  community.docker.docker_compose_v2:
    project_src: "{{ tailscale_parent_dir }}"
    pull: "{{ docker_image_pull_action }}"
    state: present
    remove_orphans: true

- name: Tailscale Split DNS Configuration
  block:
    # curl -u "{{ OAUTH_ID }}:{{ OAUTH_SECRET }}" \
    #   -d "grant_type=client_credentials" \
    #   https://api.tailscale.com/api/v2/oauth/token
    - name: OAuth Access Token Retrieval
      ansible.builtin.uri:
        url: "https://api.tailscale.com/api/v2/oauth/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ tailscale_oauth_id }}"
          client_secret: "{{ tailscale_oauth_secret }}"
          grant_type: "client_credentials"
      register: oauth
      delegate_to: localhost

    # curl -X POST \
    #   -H "Authorization: Bearer {{ ACCESS_TOKEN }}" \
    #   -H "Content-Type: application/json" \
    #   -d '{
    #     "nameservers": [{"address": "{{ MGMT01_IP_ADDRESS }}", "useWithExitNode": false}],
    #     "splitDNS": {"{{ DOMAIN_NAME }}": [{"address": "{{ DC01_IP_ADDRESS }}", "useWithExitNode": false}]},
    #     "preferences": {"overrideLocalDNS": true, "magicDNS": true}
    #   }' \
    #   "https://api.tailscale.com/api/v2/tailnet/{{ TAILNET_ID }}/dns/configuration"
    - name: Tailscale DNS Settings Configuration
      ansible.builtin.uri:
        url: "https://api.tailscale.com/api/v2/tailnet/{{ tailnet_id }}/dns/configuration"
        method: POST
        headers:
          Authorization: "Bearer {{ oauth.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "nameservers": [
              {
                "address": "{{ hostvars['KVM-MGMT01'].ansible_host }}",
                "useWithExitNode": false
              }
            ],
            "splitDNS": {
              "{{ domain_name }}": [
                {
                  "address": "{{ hostvars['KVM-DC01'].ansible_host }}",
                  "useWithExitNode": false
                }
              ]
            },
            "preferences": {
              "overrideLocalDNS": true,
              "magicDNS": true
            }
          }
        status_code: 200
      delegate_to: localhost